name = "spino-gambino-casino-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spino-gambino-casino.es"
HMAC_KEY = "a53d74b31d379df4e3c488fd09bd464c91abb62e56d0e5b69c28ad80909afe9a"
COOKIE_NAME = "s9d"
PLAY_PATH = "begin"
BUTTON_ID = "p4d40dbadadfcf594751fcb66ad0ec542"
GATE_SALT = "6d1010b6815c037c"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "45t8"
CTA_SELECTOR = ".play-button"
